# Generated by Django 3.1.5 on 2021-01-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_projekcija_broj_prodanih_karata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='seat_number',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
